export const strings = {
  bot_name: 'M32 Bot',
  welcome: 'Your AI-powered partner',
  signup: 'Sign Up',
  signin: 'Sign In',
  login: 'Login',
  create_account: 'Create Account',
  full_name: 'Full Name',
  enter_full_name: 'Enter your full name',
  email: 'Email',
  enter_email: 'Enter your email',
  password: 'Password',
  enter_password: 'Enter your password',
  already_have_account: 'Already have an account?',
  do_not_have_account: `Don't have an account?`,
  // Validation
  invalid_email: 'Invalid email',
  email_required: 'Email is required',
  password_required: 'Password is required',
  password_min: 'Password must be at least 6 characters',
  name_required: 'Name is required',
  name_min: 'Name must be at least 5 characters',
};
